# Generated by Django 3.2.5 on 2021-07-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('genre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coresite.genre')),
                ('genre_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to='coresite.genre')),
            ],
            bases=('coresite.genre',),
        ),
    ]
