# Generated by Django 3.2.5 on 2021-07-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='genre_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre', to='coresite.genre'),
        ),
    ]
