# Generated by Django 3.2.5 on 2021-07-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0002_alter_subgenre_genre_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
                ('type', models.CharField(choices=[('TV', 'TV Series'), ('OVA', 'OVA'), ('FILM', 'FILM')], max_length=30)),
                ('date_aired', models.DateTimeField(verbose_name='Airing started')),
                ('date_aired_end', models.DateTimeField(verbose_name='Airing ended')),
                ('status', models.CharField(choices=[('Airing', 'Airing'), ('Ended', 'Ended')], max_length=50, verbose_name='Status')),
                ('rating', models.PositiveSmallIntegerField(choices=[('Insignificantly', 1), ('Ugly', 2), ('Bad', 3), ('Anyhow', 4), ('Mediocre', 5), ('Not bad', 6), ('Good', 7), ('Great', 8), ('Superb', 9), ('Masterpiece', 10)])),
                ('views', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(to='coresite.Genre', verbose_name='Categories')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coresite.studio')),
            ],
        ),
    ]
