# Generated by Django 3.2.5 on 2021-07-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0003_anime_studio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'managed': True, 'ordering': ['title', '-rating'], 'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': True, 'ordering': ['-title'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'managed': True, 'ordering': ['-name'], 'verbose_name': 'Studio', 'verbose_name_plural': 'Studios'},
        ),
        migrations.AlterModelOptions(
            name='subgenre',
            options={'managed': True, 'ordering': ['-title'], 'verbose_name': 'Sub Genre', 'verbose_name_plural': 'Sub Genres'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(choices=[('Insignificantly', 1), ('Ugly', 2), ('Bad', 3), ('Anyhow', 4), ('Mediocre', 5), ('Not bad', 6), ('Good', 7), ('Great', 8), ('Superb', 9), ('Masterpiece', 10)]),
        ),
    ]
