# Generated by Django 3.2.5 on 2021-07-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0004_auto_20210718_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='airing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(default='f', upload_to='anime/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='anime',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Insignificantly'), (2, 'Ugly'), (3, 'Bad'), (4, 'Anyhow'), (5, 'Mediocre'), (6, 'Not bad'), (7, 'Good'), (8, 'Great'), (9, 'Superb'), (10, 'Masterpiece')]),
        ),
    ]
