# Generated by Django 3.2.5 on 2021-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0005_auto_20210719_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='airing',
        ),
    ]
