# Generated by Django 3.2.5 on 2021-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0006_remove_anime_airing'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=models.SlugField(default='dummy-anime', verbose_name='Slug'),
        ),
    ]
