# Generated by Django 3.2.5 on 2021-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='series',
            field=models.PositiveIntegerField(default=0, verbose_name='Series'),
        ),
    ]
