# Generated by Django 3.2.5 on 2021-07-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0009_anime_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
