# Generated by Django 3.2.5 on 2021-08-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0010_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
            ],
        ),
    ]
