# Generated by Django 3.2.5 on 2021-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0012_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='f', upload_to='genre/images'),
        ),
    ]
