# Generated by Django 3.2.5 on 2021-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0013_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
