# Generated by Django 3.2.5 on 2021-08-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coresite', '0017_animeabandoned_animeloved_animewatched_animewillwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_watched', models.BooleanField(default=False)),
                ('anime_will_watch', models.BooleanField(default=False)),
                ('anime_abandoned', models.BooleanField(default=False)),
                ('anime_loved', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coresite.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='animeloved',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='animeloved',
            name='user',
        ),
        migrations.RemoveField(
            model_name='animewatched',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='animewatched',
            name='user',
        ),
        migrations.RemoveField(
            model_name='animewillwatch',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='animewillwatch',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnimeAbandoned',
        ),
        migrations.DeleteModel(
            name='AnimeLoved',
        ),
        migrations.DeleteModel(
            name='AnimeWatched',
        ),
        migrations.DeleteModel(
            name='AnimeWillWatch',
        ),
    ]
