# Generated by Django 3.2.5 on 2021-08-26 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coresite', '0018_auto_20210823_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='video_name',
        ),
        migrations.AddField(
            model_name='player',
            name='videos',
            field=models.ManyToManyField(to='coresite.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='Bebr', max_length=240),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='f', upload_to=''),
        ),
        migrations.AlterField(
            model_name='animeuserstatus',
            name='anime_abandoned',
            field=models.BooleanField(default=False, verbose_name='Abandoned'),
        ),
        migrations.AlterField(
            model_name='animeuserstatus',
            name='anime_loved',
            field=models.BooleanField(default=False, verbose_name='Loved'),
        ),
        migrations.AlterField(
            model_name='animeuserstatus',
            name='anime_watched',
            field=models.BooleanField(default=False, verbose_name='Watched'),
        ),
        migrations.AlterField(
            model_name='animeuserstatus',
            name='anime_will_watch',
            field=models.BooleanField(default=False, verbose_name='Will Watch'),
        ),
        migrations.AlterUniqueTogether(
            name='animeuserstatus',
            unique_together={('user', 'anime')},
        ),
    ]
