# Generated by Django 3.2.5 on 2021-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0019_auto_20210826_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='anime_type',
            field=models.CharField(blank=True, choices=[('TV', 'TV Series'), ('OVA', 'OVA'), ('FILM', 'FILM')], max_length=15),
        ),
        migrations.AddField(
            model_name='video',
            name='quality',
            field=models.CharField(blank=True, choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=15),
        ),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(max_length=240),
        ),
    ]
