# Generated by Django 3.2.5 on 2021-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0020_auto_20210826_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='episode',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.IntegerField(blank=True),
        ),
    ]
