# Generated by Django 3.2.5 on 2021-08-26 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coresite', '0022_auto_20210826_1100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnimeRationg',
            new_name='UserAnimeRating',
        ),
    ]
