# Generated by Django 3.2.5 on 2021-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0024_player_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuserstatus',
            name='graded',
            field=models.BooleanField(default=False, verbose_name='Graded'),
        ),
    ]
