# Generated by Django 3.2.5 on 2021-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0025_animeuserstatus_graded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboba', models.CharField(max_length=54)),
            ],
        ),
    ]
