# Generated by Django 3.2.5 on 2021-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coresite', '0026_bulba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulba',
        ),
    ]
